apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: web-app
spec:
  restartPolicy: Never
  containers:
  - name: frontend
    image: udhaya21/logmanagement-ui
    ports:
    - containerPort: 3003
  - name: netflix
    image: sambathkumarj/web
    ports:
    - containerPort: 80

